### PR TITLE
 Fix Jet Spring Boot Starter config property issues

### LINKED ISSUE #70: [Jet Springboot] System property for hazelcast.jet.config does not work without protocol
If system propery for `hazelcast.jet.config` contains path to file but URL does not include protocol then file is not loaded and exception is thrown. This works fine for `hazelcast.config` without protocol.

This works:
```
System.setProperty("hazelcast.config", "/home/user/hz.xml");
```

This doesn't work:
```
System.setProperty("hazelcast.jet.config", "/home/user/hz-jet.xml");
```

It should be consistent since it can be confusing for users.

It fails with exception like:
```
java.lang.IllegalArgumentException: Hazelcast Jet configuration does not exist 'class path resource [/home/user/hz-jet.xml]'
	at org.springframework.util.Assert.isTrue(Assert.java:136)
	at com.hazelcast.jet.contrib.autoconfigure.HazelcastJetProperties.resolveConfigLocation(HazelcastJetProperties.java:62)
	at com.hazelcast.jet.contrib.autoconfigure.HazelcastJetServerConfiguration$HazelcastJetServerConfigFileConfiguration.jetInstance(HazelcastJetServerConfiguration.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 72 more
```

### LINKED ISSUE #71: [Jet Springboot] hazelcast.config cannot be used in application.properties
Configuration from `hazelcast.config` property of `application.properties` is not taken into account for Jet instance. This works fine for `hazelcast.jet.config`.

### LINKED ISSUE #72: [Jet Springboot] Client JetInstance is not configured by ClientConfig Bean
If `@Bean` is used for `JetInstance` or `JetConfig` then `JetInstance` is autowired for them. This does not work for `ClientConfig` bean which should be autowired and Jet client instance should be created.

### LINKED ISSUE #73: [Jet Springboot] Client JetInstance cannot be configured by hazelcast.client.config system property which contains URL with protocol
If system property `hazelcast.client.config` is used to configure Jet client and the URL contains protocol then it tries to find file on incorrect path. It uses `app root path` + `hazelcast.client.config value`. It works correctly if protocol is not used there (in that case it does not try to use `app root path` for some reason).

Example: 
if system property like `System.setProperty("hazelcast.client.config", "file:/home/user/hz-jet-client.xml");` is used and springboot app is running from path `/home/user/path/to/springboot/app` then following expcetion is thrown:
```
...
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.jet.JetInstance]: Factory method 'jetInstance' threw exception; nested exception is com.hazelcast.core.HazelcastException: Config file at '/home/user/path/to/springboot/app/file:/home/user/hz-jet-client.xml' doesn't exist.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	... 124 common frames omitted
Caused by: com.hazelcast.core.HazelcastException: Config file at '/home/user/path/to/springboot/app/file:/home/user/hz-jet-client.xml' doesn't exist.
	at com.hazelcast.internal.config.AbstractConfigLocator.loadSystemPropertyFileResource(AbstractConfigLocator.java:271) ~[hazelcast-jet-4.0.jar:4.0]
	at com.hazelcast.internal.config.AbstractConfigLocator.loadFromSystemProperty(AbstractConfigLocator.java:254) ~[hazelcast-jet-4.0.jar:4.0]
	at com.hazelcast.internal.config.AbstractConfigLocator.loadFromSystemProperty(AbstractConfigLocator.java:221) ~[hazelcast-jet-4.0.jar:4.0]
	at com.hazelcast.jet.impl.config.XmlJetClientConfigLocator.locateFromSystemProperty(XmlJetClientConfigLocator.java:38) ~[hazelcast-jet-4.0.jar:4.0]
	at com.hazelcast.jet.impl.config.ConfigProvider.locateAndGetClientConfig(ConfigProvider.java:97) ~[hazelcast-jet-4.0.jar:4.0]
	at com.hazelcast.jet.Jet.newJetClient(Jet.java:180) ~[hazelcast-jet-4.0.jar:4.0]
	at com.hazelcast.jet.contrib.autoconfigure.HazelcastJetClientConfiguration$HazelcastJetClientConfigFileConfiguration.jetInstance(HazelcastJetClientConfiguration.java:62) ~[hazelcast-jet-spring-boot-starter-2.0.0-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	... 125 common frames omitted
```

### PR DESCRIPTION
**Pull request by gurbuzali**
### What this PR does / why do we need it:

Change config property for server so that it differs from the system property
Introduce IMDG config property
Fix ClientConfig bean issue
rename/restructure classes/packages

#### Which issue this PR fixes
  - fixes #70
  - fixes #71
  - fixes #72
  - fixes #73

#### Notes to your reviewer:             

Documentation part 
https://github.com/hazelcast/hazelcast-jet/pull/2177

#### Checklist

- [X] Signed the Hazelcast CLA
- [X] No checkstyle issues (`./gradlew check`)
- [x] No tests failures (`./gradlew test`)
- [X] Documentation which complies with README template (see `templates/README.template.md`).
- [X] Update `List of modules` section on the root README with your module.

### CODE REVIEW

**Comment by olukas** [comment]
With these changes I see new issues:
- `ClientConfig` bean has highest priority now (even higher then `JetConfig` bean)
- Following is logged if application property with `hazelcast.jet.server.config` is used (and if it is really used then it is logged twice):
```
[ INFO] [c.h.i.c.AbstractConfigLocator] Loading 'hazelcast-jet-member-default.yaml' from the classpath.
```
- if system property `hazelcast.config` is used them its loading and using is logged twice

However I suggest to merge this one and open new issues for aforementioned problems.

File: hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/autoconfigure/properties/AbstractConfigProperty.java [hunk 1]
```diff
@@ -14,17 +14,15 @@
...
-package com.hazelcast.jet.contrib.autoconfigure;
+package com.hazelcast.jet.contrib.autoconfigure.properties;
 
-import org.springframework.boot.context.properties.ConfigurationProperties;
 import org.springframework.core.io.Resource;
 import org.springframework.util.Assert;
 
 /**
- * Configuration properties for the hazelcast jet integration.
+ * todo add proper javadoc
```
Comment (frant-hartm) [inline hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/autoconfigure/properties/AbstractConfigProperty.java:23]: Either add proper javadoc or remove entirely.

**Comment by gurbuzali** [comment]
verify
