### PR TITLE
Use ConcurrentLinkedQueue to buffer the messages

### LINKED ISSUE #89: New item is needed to read items stored in accumulateItems after client is connected to HTTP sink
When HTTP sink is set up with `accumulateItems` and new client is connected to HTTP sink then it is able to obtain data from `accumulateItems` only if some new item is drained into sink.

Steps to reproduce:
1) Start pipeline:
```
Pipeline p = Pipeline.create();
StreamSource<Long> source = HttpListenerSources.builder()
        .type(Long.class)
        .build();
Sink<Object> sink = HttpListenerSinks.builder()
        .accumulateItems(500)
        .buildServerSent();
p.readFrom(source)
        .withoutTimestamps()
        .writeTo(sink);
```
2) Send item to HTTP source by `curl -i -X POST -d "1" http://localhost:8080`
3) Connect client for HTTP sink by `curl -X GET http://localhost:8081` - no data will be read even if there is one message stored
4) Send another item to HTTP source by `curl -i -X POST -d "2" http://localhost:8080` - this and previous message will be read by client connected to sink

### PR DESCRIPTION
**Pull request by gurbuzali**
Http Listener sink accumulates the messages in an ArrayList
and sends them when a client connects. But this should be
triggered by a new item from the upstream.

By converting the ArrayList to ConcurrentLinkedQueue, it is
now possible to send the accumulated messages from the
thread which accepts the client connections. With this
change we don't need to wait for a new item from upstream
to trigger sending the accumulated messages.

fixes #89

- [X] Signed the Hazelcast CLA
- [X] No checkstyle issues (`./gradlew check`)
- [X] No tests failures (`./gradlew test`)
- [NA] Documentation which complies with README template (see `templates/README.template.md`).
- [NA] Update `List of modules` section on the root README with your module.

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `jet-contrib-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-contrib-pr-builder/367/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-contrib-pr-builder/367/jet-contrib-pr-builder-367.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</details>
</pre>

File: http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java [hunk 1]
```diff
@@ -117,8 +118,11 @@ private void drainBuffer() {
         if (messageBuffer == null) {
             return;
         }
-        messageBuffer.forEach(sinkHttpHandler::send);
-        messageBuffer.clear();
+        String message = messageBuffer.poll();
+        while (message != null) {
+            sinkHttpHandler.send(message);
+            message = messageBuffer.poll();
+        }
```
Comment (viliam-durina) [inline http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java:125]:
```suggestion
        for (String message; (message = messageBuffer.poll()) != null; ) {
            sinkHttpHandler.send(message);
        }
```

File: http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java [hunk 2]
```diff
@@ -66,8 +66,9 @@ public HttpListenerSinkContext(
             @Nonnull FunctionEx<T, String> toStringFn
     ) {
         this.accumulateLimit = accumulateLimit;
-        this.messageBuffer = accumulateLimit > 0 ? new ArrayList<>(accumulateLimit) : null;
-        this.sinkHttpHandler = sinkType == WEBSOCKET ? new WebSocketSinkHttpHandler() : new ServerSentSinkHttpHandler();
+        this.messageBuffer = accumulateLimit > 0 ? new ConcurrentLinkedQueue<>() : null;
```
Comment (viliam-durina) [inline http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java:69]: Code style: we could make the `messageBuffer` not-null always and eliminate some of the ifs below. In case of zero limit we can use a non-concurrent queue to save on volatile reads.

File: http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java [hunk 3]
```diff
@@ -142,8 +146,13 @@ private void putToBuffer(T item) {
...
         private final Set<WebSocketChannel> peerConnections;
 
-        WebSocketSinkHttpHandler() {
+        WebSocketSinkHttpHandler(ConcurrentLinkedQueue<String> messageBuffer) {
             handler = Handlers.websocket((exchange, channel) -> {
+                String message = messageBuffer.poll();
+                while (message != null) {
+                    send(message);
+                    message = messageBuffer.poll();
+                }
```
Comment (viliam-durina) [inline http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java:155]: Can't we just call `drainBuffer`? Also, isn't NPE possible here if the `messageBuffer` is null?

File: http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java [hunk 4]
```diff
@@ -169,8 +178,14 @@ public boolean hasConnectedClients() {
         private final ServerSentEventHandler handler;
         private final Set<ServerSentEventConnection> connections;
 
-        ServerSentSinkHttpHandler() {
-            handler = Handlers.serverSentEvents();
+        ServerSentSinkHttpHandler(ConcurrentLinkedQueue<String> messageBuffer) {
+            handler = Handlers.serverSentEvents((connection, lastEventId) -> {
+                String message = messageBuffer.poll();
```
Comment (viliam-durina) [inline http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java:183]: Again

File: http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java [hunk 5]
```diff
@@ -117,8 +118,11 @@ private void drainBuffer() {
...
-        messageBuffer.forEach(sinkHttpHandler::send);
-        messageBuffer.clear();
+        String message = messageBuffer.poll();
+        while (message != null) {
+            sinkHttpHandler.send(message);
+            message = messageBuffer.poll();
+        }
     }
 
     private void putToBuffer(T item) {
```
Comment (viliam-durina) [inline http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java:128]: Do I understand this correctly? For example, if we buffer 10 items and there's no client connected, we'll accumulate the first 10 items and throw away the rest. When a client connects, we'll send the old 10 items? Sounds weird.

File: http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java [hunk 6]
```diff
@@ -49,10 +49,10 @@
 
     private final SinkHttpHandler sinkHttpHandler;
     private final Undertow undertow;
-    private final ArrayList<String> messageBuffer;
     private final FunctionEx<T, String> toStringFn;
     private final Ringbuffer<String> ringBuffer;
     private final int accumulateLimit;
+    private final ConcurrentLinkedQueue<String> messageBuffer;
 
     public HttpListenerSinkContext(
```
Comment (viliam-durina) [inline http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java:57]: Can't comment to lines not changed in this PR, so doing it here.

1. Isn't there a race in `receive` fn: we check if there's a client connected and either send directly or put to buffer. But what if a client disconnects in the meantime, will that item be lost?

2. Do we need the `flush` method? It's called immediately after `receive` and will do some work only if there wasn't a client and one connected in the meantime, but that's handled in the callback.

File: http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java (hunk 1 above)
Comment (gurbuzali) [reply http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java]: 👍

File: http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java (hunk 2 above)
Comment (gurbuzali) [reply http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java]: 👍

File: http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java (hunk 3 above)
Comment (gurbuzali) [reply http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java]: drain is not available in `ConcurrentLinkedQueue`, handled NPE with a noop message buffer

File: http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java (hunk 4 above)
Comment (gurbuzali) [reply http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java]: 👍

File: http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java (hunk 5 above)
Comment (gurbuzali) [reply http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java]: I've changed the logic so that last 10 items are returned to the client

File: http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java (hunk 6 above)
Comment (gurbuzali) [reply http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java:57]: 1. Yes, there is a race there, the real problem is undertow does not understand that a client disconnected without trying to send some items to that client.

2. removed it

File: http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java (hunk 2 above)
Comment (viliam-durina) [reply http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java]: I thought you could you `Queue<String>` for the `messageBuffer` and here do this:
```java
this.messageBuffer = accumulateLimit > 0 ? new ConcurrentLinkedQueue<>() : new LinkedList<>();
```
Without any ad-hoc classes...

Comment (viliam-durina) [reply http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java]: I take it back, I noticed you also address other concerns here.

File: http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java [hunk 7]
```diff
@@ -137,14 +118,56 @@ private void putToBuffer(T item) {
         boolean hasConnectedClients();
     }
 
+    interface MessageBuffer {
```
Comment (viliam-durina) [inline http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java:121]: Why don't we mark this and all other interfaces and classes in this class `private`?

**Review by viliam-durina — APPROVED** [review]

File: http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java (hunk 7 above)
Comment (gurbuzali) [reply http/src/main/java/com/hazelcast/jet/contrib/http/impl/HttpListenerSinkContext.java:121]: I've seen your approve and just merged the PR withtout addressing this. good idea, I'll do it in a separate PR.
